# -*- coding: utf-8 -*-
"""projeto 105

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fsS7lOlowQnz5D08vXBQAImf2eOo0nlm
"""

from google.colab import files 
data_to_load = files.upload()
import csv

import pandas as pd
import plotly.express as pe

with open("data.csv") as f2:
  reader2 = csv.reader(f2)
  file_data2 = list(reader2)
  data = file_data2[0]
totalNotas = 0
quantidade = len(file_data2)
for i in file_data2:
  totalNotas+= float(i[1])
media = totalNotas/quantidade
print("A média de notas dos alunos é", media)

def media(dados):
  quantidade = len(dados)
  total = 0
  for y in dados:
    total += int(y)
  media = total/quantidade
  return media

import math 
listaQuadrada = []
for a in data:
  numero = int(a)-media(data)
  numero = numero **2
  listaQuadrada.append(numero)
soma = 0
for q in listaQuadrada:
  soma += q
resultado = soma/(len(data)-1)
derivacao = math.sqrt(resultado)
print(listaQuadrada)
print(soma)
print(resultado)
print(derivacao)